default_config:

mqtt:

automation: !include automations.yaml

recorder:
  purge_keep_days: 360
  auto_purge: true
  commit_interval: 60

  include:
    entities:
      - sensor.adafruit_scd41_co2
      - sensor.adafruit_scd41_temperature
      - sensor.adafruit_scd41_humidity

  exclude:
    domains:
      - updater
